// Auto-generated TypeScript definitions for book-learn.module.scss
declare const styles: {
  readonly bookLearn: string;
  readonly learnHeader: string;
  readonly backLink: string;
  readonly learnContent: string;
  readonly unitsSidebar: string;
  readonly sidebarHeader: string;
  readonly unitsList: string;
  readonly unitItem: string;
  readonly unitHeader: string;
  readonly active: string;
  readonly unitIcon: string;
  readonly unitTitle: string;
  readonly expandIcon: string;
  readonly expanded: string;
  readonly unitSections: string;
  readonly sectionLink: string;
  readonly sectionIcon: string;
  readonly learnMain: string;
  readonly emptyState: string;
  readonly emptyIcon: string;
  readonly unitContent: string;
  readonly unitHeaderInfo: string;
  readonly unitSummary: string;
  readonly contentSections: string;
  readonly contentCard: string;
  readonly cardIcon: string;
  readonly vocabulary: string;
  readonly grammar: string;
  readonly exercise: string;
  readonly flashcard: string;
  readonly cardContent: string;
  readonly itemCount: string;
  readonly unitProgress: string;
  readonly progressBar: string;
  readonly progressFill: string;
  readonly grammarViewer: string;
  readonly grammarCard: string;
  readonly grammarTitle: string;
  readonly grammarContent: string;
  readonly grammarExample: string;
  readonly exampleContent: string;
};

export default styles;
